// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sparkplug_b.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package org.eclipse.tahu.protobuf;

