// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zProductionLine = z.object({
    id: z.uuid(),
    name: z.string(),
    factoryId: z.uuid(),
    isa95Role: z.enum([
        'WORK_CENTER',
        'WORK_UNIT',
        'PRODUCTION_LINE'
    ])
});

export const zLineStateSnapshot = z.object({
    lineId: z.uuid(),
    state: z.enum([
        'RUNNING',
        'IDLE',
        'DOWN',
        'CHANGEOVER'
    ]),
    since: z.iso.datetime()
});

export const zOeeReading = z.object({
    lineId: z.uuid(),
    window: z.enum([
        '5m',
        '1h',
        'shift'
    ]),
    oee: z.number().gte(0).lte(1),
    availability: z.number().gte(0).lte(1),
    performance: z.number().gte(0).lte(1),
    quality: z.number().gte(0).lte(1),
    observedAt: z.iso.datetime()
});

/**
 * ok
 */
export const zGetApiV1LinesResponse = z.array(zProductionLine);

export const zGetApiV1LinesByLineIdStatePath = z.object({
    lineId: z.uuid()
});

/**
 * ok
 */
export const zGetApiV1LinesByLineIdStateResponse = zLineStateSnapshot;

export const zGetApiV1LinesByLineIdOeePath = z.object({
    lineId: z.uuid()
});

export const zGetApiV1LinesByLineIdOeeQuery = z.object({
    window: z.enum([
        '5m',
        '1h',
        'shift'
    ]).optional().default('5m')
});

/**
 * ok
 */
export const zGetApiV1LinesByLineIdOeeResponse = zOeeReading;
