# generated by datamodel-codegen:
#   filename:  sdf-api.yaml

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, confloat


class Isa95Role(StrEnum):
    WORK_CENTER = 'WORK_CENTER'
    WORK_UNIT = 'WORK_UNIT'
    PRODUCTION_LINE = 'PRODUCTION_LINE'


class ProductionLine(BaseModel):
    id: UUID
    name: str
    factoryId: UUID
    isa95Role: Isa95Role


class State(StrEnum):
    RUNNING = 'RUNNING'
    IDLE = 'IDLE'
    DOWN = 'DOWN'
    CHANGEOVER = 'CHANGEOVER'


class LineStateSnapshot(BaseModel):
    lineId: UUID
    state: State
    since: AwareDatetime


class Window(StrEnum):
    field_5m = '5m'
    field_1h = '1h'
    shift = 'shift'


class OeeReading(BaseModel):
    lineId: UUID
    window: Window
    oee: confloat(ge=0.0, le=1.0)
    availability: confloat(ge=0.0, le=1.0)
    performance: confloat(ge=0.0, le=1.0)
    quality: confloat(ge=0.0, le=1.0)
    observedAt: AwareDatetime
