# generated by datamodel-codegen:
#   filename:  line_state.schema.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict


class State(StrEnum):
    RUNNING = 'RUNNING'
    IDLE = 'IDLE'
    DOWN = 'DOWN'
    CHANGEOVER = 'CHANGEOVER'


class LineStateEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tenantId: str
    lineId: UUID
    state: State
    reason: str | None = None
    observedAt: AwareDatetime
