# generated by datamodel-codegen:
#   filename:  machine_telemetry.schema.json

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint


class Metric(StrEnum):
    cycle_count = 'cycle_count'
    good_count = 'good_count'
    scrap_count = 'scrap_count'
    state = 'state'
    cycle_time_ms = 'cycle_time_ms'


class MachineTelemetry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tenantId: str
    lineId: UUID
    machineId: UUID
    metric: Metric
    value: float | str
    observedAt: AwareDatetime
    sparkplugSeq: conint(ge=0, le=255)
