#!/usr/bin/env bash
# scripts/stats.sh — regenerate the codebase metrics surfaced in README.md.
#
# Two metrics, both measured fresh (never hand-typed): lines of code per language
# and test coverage per app. Coverage is reported two ways — overall and for the
# functional core alone (any path under `domain/` or `shared_kernel/`) — because
# the imperative shell (MQTT / Kafka / Spring / FastAPI adapters) is exercised by
# opt-in testcontainers integration tests, not the unit run measured here.
#
# Prereqs: `bash scripts/init.sh` first (per-app .venv + Kotlin toolchain). Needs
# `uv`, a JDK 21, and `python3` on PATH. Unit run only — no Docker required.
#
# Usage:
#   bash scripts/stats.sh            # print the metrics block to stdout
#   bash scripts/stats.sh --write    # also rewrite the block between the
#                                     #   <!-- BEGIN stats --> / <!-- END stats -->
#                                     #   markers in README.md
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
cd "$ROOT"
WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1

# A source file belongs to the functional core when its path carries one of these
# segments. Kept as one rule across languages so the split stays honest.
CORE_RE='/(domain|shared_kernel)/'

# --- 1. Lines of code (find + wc; no external counter needed) ----------------
# Excludes generated code, vendored deps and build output — the same exclusions
# the architecture rules treat as "not authored here".
loc() { # <ext> <path-filter...>
  local ext="$1"; shift
  find apps packages -name "*.$ext" \
    -not -path '*/.venv/*' -not -path '*/build/*' -not -path '*/.gradle/*' \
    -not -path '*/node_modules/*' -not -path '*/__pycache__/*' -not -path '*/codegen/*' \
    "$@" -exec wc -l {} + 2>/dev/null | awk '!(NF == 2 && $2 == "total") { sum += $1 } END { print sum + 0 }'
}

PY_SRC=$(loc py -path '*/src/*'); PY_TEST=$(loc py -path '*/tests/*'); PY_TOTAL=$((PY_SRC + PY_TEST))
KT_SRC=$(loc kt -path '*/src/main/*'); KT_TEST=$(loc kt -path '*/src/test/*'); KT_TOTAL=$((KT_SRC + KT_TEST))

# --- 2. Python coverage (pytest-cov, one unit run per app, JSON parsed) -------
py_cov() { # <app-dir> -> "<overall> <core>"
  local app="$1" json
  json="$(mktemp)"
  ( cd "$app" && uv run pytest --cov=src --cov-report="json:$json" -q >/dev/null 2>&1 ) || { echo "n/a n/a"; rm -f "$json"; return; }
  python3 - "$json" <<'PY'
import json, re, sys
data = json.load(open(sys.argv[1]))
core_re = re.compile(r'/(domain|shared_kernel)/')
def pct(stmts):
    cov = sum(f["summary"]["covered_lines"] for f in stmts)
    tot = sum(f["summary"]["num_statements"] for f in stmts)
    return f"{round(cov / tot * 100)}%" if tot else "n/a"
files = data["files"]
allf = list(files.values())
core = [v for k, v in files.items() if core_re.search(k.replace("\\", "/"))]
print(pct(allf), pct(core))
PY
  rm -f "$json"
}

read -r API_ALL API_CORE     < <(py_cov apps/api-python)
read -r INGEST_ALL INGEST_CORE < <(py_cov apps/ingest-python)

# --- 3. Kotlin coverage (Kover XML; overall + packages ending in .domain) -----
KT_DIR="apps/ot-gateway-kotlin"
( cd "$KT_DIR" && ./gradlew koverXmlReport -q --console=plain >/dev/null 2>&1 ) || true
read -r KT_ALL KT_CORE < <(python3 - "$KT_DIR/build/reports/kover/report.xml" <<'PY'
import sys, xml.etree.ElementTree as ET
try:
    root = ET.parse(sys.argv[1]).getroot()
except Exception:
    print("n/a n/a"); raise SystemExit
def line_counter(el):
    for c in el.findall("counter"):
        if c.get("type") == "LINE":
            return int(c.get("missed")), int(c.get("covered"))
    return 0, 0
def pct(pairs):
    miss = sum(m for m, _ in pairs); cov = sum(c for _, c in pairs)
    tot = miss + cov
    return f"{round(cov / tot * 100)}%" if tot else "n/a"
overall = [line_counter(root)]
core = [line_counter(p) for p in root.findall("package") if p.get("name", "").endswith("/domain")]
print(pct(overall), pct(core))
PY
)

# --- 4. Emit the markdown block ----------------------------------------------
STAMP="$(date +%Y-%m-%d) @ $(git rev-parse --short HEAD)"
block() {
  cat <<EOF
<!-- BEGIN stats (generated by scripts/stats.sh — do not edit by hand) -->
_Generated by \`scripts/stats.sh\` on ${STAMP}._

**Lines of code** (authored; generated/vendored/build output excluded)

| Language | Total | src/main | tests |
|----------|------:|---------:|------:|
| Python   | ${PY_TOTAL} | ${PY_SRC} | ${PY_TEST} |
| Kotlin   | ${KT_TOTAL} | ${KT_SRC} | ${KT_TEST} |

**Test coverage** (line coverage, unit run only) — the imperative shell (MQTT /
Kafka / Spring / FastAPI adapters) is covered by opt-in testcontainers integration
tests, so it reads as uncovered in the *overall* column. The *functional core*
column (everything under \`domain/\` + \`shared_kernel/\`) is the figure that
reflects the tested design surface.

| App | Overall | Functional core |
|-----|--------:|----------------:|
| \`apps/api-python\`        | ${API_ALL}    | ${API_CORE} |
| \`apps/ingest-python\`     | ${INGEST_ALL} | ${INGEST_CORE} |
| \`apps/ot-gateway-kotlin\` | ${KT_ALL}     | ${KT_CORE} |
<!-- END stats -->
EOF
}

OUT="$(block)"
printf '%s\n' "$OUT"

if [ "$WRITE" -eq 1 ]; then
  STATS_BLOCK="$OUT" python3 - "$ROOT/README.md" <<'PY'
import os, re, sys
p = sys.argv[1]
s = open(p, encoding="utf-8").read()
block = os.environ["STATS_BLOCK"]
pat = re.compile(r"<!-- BEGIN stats.*?<!-- END stats -->", re.S)
if pat.search(s):
    # re.sub treats backslashes in the replacement specially; pass a function to
    # insert the block verbatim.
    open(p, "w", encoding="utf-8").write(pat.sub(lambda _: block, s))
    print("README.md stats block updated.", file=sys.stderr)
else:
    print("WARN: stats markers not found in README.md; nothing written.", file=sys.stderr)
PY
fi
